name: Bug Report
description: Report a behaviour that is not desired in ValheimRAFT
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        Please note that this report is for bugs **in ValheimRAFT**.
        
        If you have an issue with another plugin, contact the plugin developer first.
  - type: textarea
    id: basic-description
    attributes:
      label: What happened?
      description: Please describe a bug shortly.
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: If applicable, include the steps to reproduce the issue.
      placeholder: |
        1. In this game...
        2. With this configuration...
        3. Do this...
        4. See error...
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Log outputs
      description: |
        Please copy and paste any relevant log output.
        You can use **one or multiple** of the following log sources:
        
        - BepInEx Log: located in `BepInEx/LogOutput.log`
        - Preloader error log: located in game folder and named `preloader_<date>.log`
        - Unity Player log: `output_log.txt` or `Player.log` generated by Unity
        - Copy-paste from BepInEx console if enabled
        
        Paste only the logs. They will be automatically reformatted into code blocks.
      render: txt
  - type: textarea
    id: env
    attributes:
      label: Environment
      description: |
        Fill in information about your game.
        OS:
          - **OS**: Windows 11 | Ubuntu 20.04
          - **Graphics**: DX11 (or Vulkan)
        Mods:
          - **BepInEx**: 5.4.2202
          - Jotunn 2.15.2
          - **ValheimRAFT**: 1.7.0
        
        
        You can check ValheimRAFT version by checking the file in zolantris-ValheimRAFT/ValheimRAFT.dll or list the downloaded version from (thunderstore/nexus) you are using.
      value: |
        OS:
        - **OS**: Windows 11 | Ubuntu 20.04
        - **Graphics**: DX11 (or Vulkan)
        Mods:
        - **BepInEx**: 5.4.2202
        - Jotunn 2.15.2
        - **ValheimRAFT**: 1.7.0
      render: markdown
    validations:
      required: true